// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfpH96L82ilSKPLaLwz6OiSj8-YIa_59A',
    appId: '1:885483061123:web:46d8436a6bde67b80980b6',
    messagingSenderId: '885483061123',
    projectId: 'felelamali',
    authDomain: 'felelamali.firebaseapp.com',
    storageBucket: 'felelamali.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJso65MUUXAR1Aw4nHFZCAMpiAbm7RYO0',
    appId: '1:885483061123:android:b3c11078f3ce28980980b6',
    messagingSenderId: '885483061123',
    projectId: 'felelamali',
    storageBucket: 'felelamali.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoxeIk3q0W4iPjDZ9lzr6pMa6Vzctqkq4',
    appId: '1:885483061123:ios:0ce73c081c7daa6e0980b6',
    messagingSenderId: '885483061123',
    projectId: 'felelamali',
    storageBucket: 'felelamali.firebasestorage.app',
    iosBundleId: 'com.example.fefelaMaliApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoxeIk3q0W4iPjDZ9lzr6pMa6Vzctqkq4',
    appId: '1:885483061123:ios:0ce73c081c7daa6e0980b6',
    messagingSenderId: '885483061123',
    projectId: 'felelamali',
    storageBucket: 'felelamali.firebasestorage.app',
    iosBundleId: 'com.example.fefelaMaliApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfpH96L82ilSKPLaLwz6OiSj8-YIa_59A',
    appId: '1:885483061123:web:15f6d55ed5538b2a0980b6',
    messagingSenderId: '885483061123',
    projectId: 'felelamali',
    authDomain: 'felelamali.firebaseapp.com',
    storageBucket: 'felelamali.firebasestorage.app',
  );
}
